### ISSUE TITLE
Problem with burger simbol for folding menu in Django navbar

### ISSUE THREAD

**Issue by gilleswx** [rokdd/django-static-libs#1]
Hi there,
I have done some Django projects in the past and on a project right now I am trying to include the burger symbol for a folding unfolding menu in the nav-bar using bootstrap. It didn't work so I tried with django-autostatic-libs and also including the CDN for bootstrap (css &js), and also downloading the css and js files in the static folder. Did not work properly...any recommendation?
For the django-static-libs I included it in the setting.py:
My `settings.py` is like that:
```
# Application definition

INSTALLED_APPS = [
    'projects.apps.ProjectsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_auto_static_libs',
]
.......
# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'boot'),
]
```

**Comment by rokdd** [comment]
And the include in the template?

**Comment by rokdd** [comment]
So first of all you need to declare that you want to use bootstrap in the settings.py:


```
from django_auto_static_libs.libraries import bootstrap
DJANGO_AUTO_STATIC_LIBS = {
    'libraries': {
        'bootstrap': bootstrap,
    },
    'destination_folder': 'django-auto-static-libs'
}
```


Then run once manually:
```
python manage.py static-libs-download
```
When you go with this settings it should download the files into:
```
<STATIC_ROOT>/django-auto-static-libs/bootstrap/<the files>
```
Try to check whether the files are downloaded and whether they are accessible from the browser by url.

Afterwards there should be the include in your template:

```
{% load static %}
<script src=”{% static 'django-auto-static-libs/bootstrap/js/bootstrap.min.js' %}”></script>
<link rel=”stylesheet” href=”{% static 'django-auto-static-libs/bootstrap/css/bootstrap.min.css' %}">
```

**Comment by gilleswx** [comment]
Hi there,
Thanks a lot,
I did the changes you mentioned,

Applying the command "python manage.py static-libs-download", it gives an error message:

File "/home/meteogeek/Documents/2022_01_Jan_Jul_2022/SDNLV2_Dev_Folder/SDNL1V2P0P1/SDNL1V2/settings.py", line 17, in <module>
    from django_static_libs.libraries import boostrap
ModuleNotFoundError: No module named 'django_static_libs'

But it does not make sens, since the other day I ran the pip install for it,
I redid it:
<<pip install django-auto-static-libsRequirement already satisfied: django-auto-static-libs in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (0.4.5)
Requirement already satisfied: requests in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (from django-auto-static-libs) (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (from requests->django-auto-static-libs) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (from requests->django-auto-static-libs) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (from requests->django-auto-static-libs) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages (from requests->django-auto-static-libs) (1.26.8)>>

But still give me the same problem,
It seems that I have some virtual env problems....mmm.not sure

Thanks for your time

gilles

**Comment by rokdd** [comment]
Sorry that was my mistake because I had to rename the package some time ago:

`from django_auto_static_libs.libraries import bootstrap`

**Comment by gilleswx** [comment]
Ah OK thanks!
It is already quite late over there, I really appreciate you taking the time,
Still give me this error message about providers:
```
File "/home/meteogeek/Documents/2022_01_Jan_Jul_2022/SDNLV2_Dev_Folder/SDNL1V2P0P1/SDNL1V2/settings.py", line 17, in <module>
    from django_auto_static_libs.libraries import boostrap
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django_auto_static_libs/libraries.py", line 1, in <module>
    from django_auto_static_libs.providers.GithubProvider import GithubProvider
ModuleNotFoundError: No module named 'django_auto_static_libs.providers'
```

**Comment by rokdd** [comment]
You have still a typo in boostrap ;-) . I just tried at my machines and I do not get this error... do you have copied it somehow that you have no access to the files from the python (or the user which is running python)? Do you have the folder providers?

**Comment by gilleswx** [comment]
Sorry I need new glasses...I corrected my booo mistake 
But sill I get an error message:
`ModuleNotFoundError: No module named 'django_auto_static_libs.providers'`
Here goes the full error message:
`python manage.py static-libs-download`
```
Traceback (most recent call last):
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 243, in fetch_command
    app_name = commands[subcommand]
KeyError: 'static-libs-download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 250, in fetch_command
    settings.INSTALLED_APPS
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/meteogeek/Documents/2022_01_Jan_Jul_2022/SDNLV2_Dev_Folder/SDNL1V2P0P1/SDNL1V2/settings.py", line 18, in <module>
    from django_auto_static_libs.libraries import bootstrap
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django_auto_static_libs/libraries.py", line 1, in <module>
    from django_auto_static_libs.providers.GithubProvider import GithubProvider
ModuleNotFoundError: No module named 'django_auto_static_libs.providers'


```

**Comment by gilleswx** [comment]
OK just read the last part of your comment
I am looking into it, sorry

**Comment by gilleswx** [comment]
Hi again,
Should the prviders folder should be inside the django_auto_static_libs?
I looked inside:
~/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django_auto_static_libs
But nothing there

**Comment by rokdd** [comment]
Good news... it was not your mistake, there was a bug in the `setup.py` which I fixed and pushed again to pypi. So it should install version 0.4.6 with pip. When not just uninstall and install it again.

**Comment by gilleswx** [comment]
Hi,
Thanks again,
I did that, so it is updated,
One more question, I am guessing, for the destination path, should it be the static one?
Defined with os.path.join(BASE_DIR, 'static')?

**Comment by rokdd** [comment]
Well there are two settings:

- Path for the whole folder of module `destination_folder`: 
  - if it is a absolute path it does not require STATIC_ROOT
  - else it get joined with STATIC_ROOT
- Path for each library:
  -  currently it supports only the relative name by key of the dict of settings
  -  in the future I guess it can be also implemented with different absolute paths for each library

**Comment by gilleswx** [comment]
Hi again,
I am not sure I understood your last message,
I tried to put the absolute path to the static folder,
It give me the following error:
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
Here is the full output for the python manage.py static-libs-download:
 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django_auto_static_libs/management/commands/static-libs-download.py", line 6, in <module>
    from django_auto_static_libs import settings
  File "/home/meteogeek/.local/share/virtualenvs/SDNLV2_Dev_Folder-TG8qO8ap/lib/python3.8/site-packages/django_auto_static_libs/settings.py", line 20, in <module>
    DESTINATION_ROOT=os.path.join(STATIC_ROOT,DJANGO_AUTO_STATIC_LIBS['destination_folder'])
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rokdd** [comment]
I would not recommend to set another absolute path but anyway it should work.. what did you put as a option in `settings.py` for the path?

**Comment by gilleswx** [comment]
Hi there,
Starting the day over here,
for the DJANGO_AUTO_STATIC_LIBS part you mean?
I put:
DJANGO_AUTO_STATIC_LIBS = {
    'libraries': {
        'bootstrap': bootstrap,
    },
    '/home/meteogeek/Documents/2022_01_Jan_Jul_2022/SDNLV2_Dev_Folder/SDNL1V2P0P1/static/ ': 'dajngo-auto-static-libs'
}

**Comment by rokdd** [comment]
Okay then it is clear that it is not working. Try like this:
```
DJANGO_AUTO_STATIC_LIBS = {
'libraries': {
'bootstrap': bootstrap,
},
 'destination_folder': '/home/meteogeek/Documents/2022_01_Jan_Jul_2022/SDNLV2_Dev_Folder/SDNL1V2P0P1/static/ '
}
```

**Comment by gilleswx** [comment]
OK,  made that change, thanks,
Now running the command line: python manage.py static-libs-download
I get the Download and update static lib "bootstrap" starting
But then I get the following:
Not extracted bootstrap-5.1.3/: Not matching include rule
Not extracted bootstrap-5.1.3/.babelrc.js: Not matching include rule
Not extracted bootstrap-5.1.3/.browserslistrc: Not matching include rule
Not extracted bootstrap-5.1.3/.bundlewatch.config.json: Not matching include rule
Not extracted bootstrap-5.1.3/.cspell.json: Not matching include rule
Not extracted bootstrap-5.1.3/.editorconfig: Not matching include rule
Not extracted bootstrap-5.1.3/.eslintignore: Not matching include rule
Not extracted bootstrap-5.1.3/.eslintrc.json: Not matching include rule
Not extracted bootstrap-5.1.3/.gitattributes: Not matching include rule
Not extracted bootstrap-5.1.3/.github/: Not matching include rule
Not extracted bootstrap-5.1.3/.github/CODEOWNERS: Not matching include rule
Not extracted bootstrap-5.1.3/.github/CONTRIBUTING.md: Not matching include rule
Not extracted bootstrap-5.1.3/.github/ISSUE_TEMPLATE/: Not matching include rule
Not extracted bootstrap-5.1.3/.github/ISSUE_TEMPLATE/bug_report.yml: Not matching include rule
...........................................
And so on

**Comment by rokdd** [comment]
well is there something in the folder?

**Comment by gilleswx** [comment]
If you mean in the static folder, yes,
there are 2 folders (js and css) and 2 files (logo)

**Comment by rokdd** [comment]
Good..  but it should work with the css and js folder and include them in the template?

The other files are just files which are included and not neccesary to run (and when they are necessary I can change the config to copy them as well)

**Comment by gilleswx** [comment]
OK, thanks for your feed back,
By saying "it should work with the css and js folder", you mean keeping them in there, so just let it like it is, is that correct?
I have put the tmeplates the following way:
I have in a folder call partials the  _navbar.html I call in my base.html file which is in the upper folder called templates
It is working fine most of it, just still cannot get this burger symbol pop out in the nav bar.
I am not sure where to call and how to call the js part to get that working
The css part I call it directly from the static/css folder:
 <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
But now that I included your great work I am not sure how to call these css and js things in the html files

**Comment by rokdd** [comment]
Can you post your include of the files in header?

Should be something like this:

```
{% load static %}
<script src=”{% static 'django-auto-static-libs/bootstrap/js/bootstrap.min.js' %}”></script>
<link rel=”stylesheet” href=”{% static 'django-auto-static-libs/bootstrap/css/bootstrap.min.css' %}">
```

**Comment by gilleswx** [comment]
Until now I had:
{% load static %}

<link href="{% static 'css/homepage.css' %}" rel="stylesheet">

So no I have to include the: 
<script src=”{% static 'django-auto-static-libs/bootstrap/js/bootstrap.min.js' %}”></script>
<link rel=”stylesheet” href=”{% static 'django-auto-static-libs/bootstrap/css/bootstrap.min.css' %}">

The doubt I have is that now in my static folder there is a folder without name ans inside is a bootstrap folder  with inside the css jjs and dom ones and some js and other files

So I wonder f this structure is correct or I should modify it

**Comment by gilleswx** [comment]
Until now I had:
{% load static %}
<link href="{% static 'css/homepage.css' %}" rel="stylesheet">

So no I have to include the:
<script src=”{% static 'django-auto-static-libs/bootstrap/js/bootstrap.min.js' %}”></script>
<link rel=”stylesheet” href=”{% static 'django-auto-static-libs/bootstrap/css/bootstrap.min.css' %}">

The doubt I have is that now in my static folder there is a folder without name ans inside is a bootstrap folder with inside the css jjs and dom ones and some js and other files

So I wonder f this structure is correct or I should modify it

**Comment by gilleswx** [comment]
I am doing something wrong with the post just above, it does not seem to send all the info I put in

**Comment by gilleswx** [comment]
Right now I have the {% load static %} followed by <link href="{% static 'css/homepage.css' %}" rel="stylesheet"> in the next line

**Comment by gilleswx** [comment]
So her I go again:
<code>

<link href="{% static 'css/homepage.css' %}" rel="stylesheet">
</code>

Now I have to put 
<code>
{% load static %}
<script src=”{% static 'django-auto-static-libs/bootstrap/js/bootstrap.min.js' %}”></script>
<link rel=”stylesheet” href=”{% static 'django-auto-static-libs/bootstrap/css/bootstrap.min.css' %}">
</code>
The doubt I have is that now in my static folder there is a folder without name ans inside is a bootstrap folder with inside the css jjs and dom ones and some js and other files

So I wonder f this structure is correct or I should modify it

**Comment by gilleswx** [comment]
Learning how to use github, sorry,

**Comment by gilleswx** [comment]
So far after load static I have
<code><link href="{% static 'css/homepage.css' %}" rel="stylesheet"></code>

**Comment by gilleswx** [comment]
I am trying to cite the code and even with <code></code> does not want to post it

**Comment by rokdd** [comment]
Just paste it in and mark the text and press the code button above in the editor then it is like escaped..

For steping forward: The plugin correctly supports only to download the files and not to link them in the template. So the procees how you embed your files is the same like for any static folder / file . So I would recoomend that you hard code the url of the min and js file which you want to include and make sure that this files are properly loaded.

**Comment by gilleswx** [comment]
OK, thanks,
I think I understand that,
Just before redeaing your  lastpot I did paste it 
Got this 
02/Mar/2022 16:02:17] "GET /projects/ HTTP/1.1" 200 2811
[02/Mar/2022 16:02:17] "GET /static/css/homepage.css HTTP/1.1" 304 0
Not Found: /projects/”/static/django-auto-static-libs/bootstrap/js/bootstrap.min.js”
[02/Mar/2022 16:02:17] "GET /projects/%E2%80%9D/static/django-auto-static-libs/bootstrap/js/bootstrap.min.js%E2%80%9D HTTP/1.1" 404 3046
[02/Mar/2022 16:02:17] "GET /static/css/bootstrap.css HTTP/1.1" 200 205484
[02/Mar/2022 16:02:17] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[02/Mar/2022 16:02:17] "GET /static/STC_logo.png HTTP/1.1" 200 19500

**Comment by gilleswx** [comment]
Sorry if all my questions are simple
Is that normal that in static there in a folder without name in which there is the bootstrap folder?

**Comment by rokdd** [comment]
no I guess not... a folder without name?..

I only see that you get a 404 and that you url looks not very healthy:

- you have to point to your absolute path you are using. so when you do not have a absolute path with "django-auto-static-libs" then you should not include it in the url.. you will need like `<your absolute url path>/bootstrap/css/bootstrap.min.css`
- you have a quote in the url.. and `projects`.

From the absolute url you sent before it should be: `/static/bootstrap/css/bootstrap.min.css`
Can you maybe make a screenshot of the folder under static or list it somehow?

**Comment by gilleswx** [comment]
Yes sure, here goes a screenshot
![static](https://user-images.githubusercontent.com/63735619/156410567-6f8be64a-ba4f-48f0-8823-c3e64e6e72ac.png)

**Comment by gilleswx** [comment]
The bootstrap folder is inside the folder without name on the left

**Comment by gilleswx** [comment]
So I wonder if I could simply rename with whatever name that folder and put it in the full path

**Comment by rokdd** [comment]
Sure simply rename.. can you unfold or just make a small summary what is in each folder... but when you have no bootstrap folder then you also have to remove the bootstrap folder from the url.. it is simple like a img.. you need the path to the js and the css file. everything else is bootstrap loading

**Comment by gilleswx** [comment]
OK, I did so,
Inside static:
-the css folder has on homemade css file and all the previously downloaded css bootstrap ones
-the js one has all the previously downloaded bootstrap js files
Inisde the folder iwthout name (I renamed it stf for now) is the bootstrap folder with the following shown in the screenshot:
![insidebootstrapfolder](https://user-images.githubusercontent.com/63735619/156414028-2fee58dd-3109-46c1-95a3-918057c9f403.png)

**Comment by rokdd** [comment]
OK.. then put the path together with stf included and it should be work to load in the template / browser?

**Comment by gilleswx** [comment]
The problem I see using absolute path is that after if I move the project somewhere else I would have to go in and modify it  manually each time

**Comment by gilleswx** [comment]
So I used:
```
<script src="{% static 'stf/bootstrap/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'stf/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'stf/bootstrap/css/bootstrap.css' %}">
```

**Comment by gilleswx** [comment]
And it found the files no problem

**Comment by gilleswx** [comment]
Now I need to figure out the js and css files I need to get the folding/unfolding list and the burger icon

**Comment by rokdd** [comment]
Well, I guess you should only use min or not min for css, not both. Well as I said I do not know bootstrap very well. Just double check that in the Browser Network are no 404 because bootstrap might load additionally files in background. Else, I do not know where the error appears, and I guess it is not related to this package anymore (hopefully). Just read through[ how initialize..](https://getbootstrap.com/docs/3.4/javascript/#buttons) hope you will manage ;-)

**Comment by gilleswx** [comment]
Ok I will try with iwth only one of the 2 and see which one works out!
I have no more 404 now, so that is much better
Thanks for your guidance and help, it is more than appreciated :)
